apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "oficina_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  APP_ENV: "production"
  APP_DEBUG: "false"
  DD_ENV: "prod"
  DD_SERVICE: "oficina-mecanica-api"
  DD_VERSION: "2.0.0"
  OBSERVABILITY_LOG_FORMAT: "json"
  PROMETHEUS_ENABLED: "true"
