"""Add orcamento_aprovado flag to OrdemServico

Revision ID: 48126106b1df
Revises: e62506a3852c
Create Date: 2026-05-01 18:47:07.434549

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48126106b1df'
down_revision: Union[str, None] = 'e62506a3852c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.add_column('ordens_servico', sa.Column('orcamento_aprovado', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_historico_id'), 'ordens_servico_historico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_pecas_id'), 'ordens_servico_pecas', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_servicos_id'), 'ordens_servico_servicos', ['id'], unique=False)
    op.create_index(op.f('ix_pecas_id'), 'pecas', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_unique_constraint(None, 'servicos', ['nome'])
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('veiculos', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.alter_column('veiculos', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_constraint(None, 'servicos', type_='unique')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_index(op.f('ix_pecas_id'), table_name='pecas')
    op.drop_index(op.f('ix_ordens_servico_servicos_id'), table_name='ordens_servico_servicos')
    op.drop_index(op.f('ix_ordens_servico_pecas_id'), table_name='ordens_servico_pecas')
    op.drop_index(op.f('ix_ordens_servico_historico_id'), table_name='ordens_servico_historico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_column('ordens_servico', 'orcamento_aprovado')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    # ### end Alembic commands ###
